# Chapter 04 — NumPy Basics: Arrays and Vectorized Computation

**Book:** Python for Data Analysis (Wes McKinney, 3E)
**Date started:** 0226-05-04
**Date closed:** 
**Time invested:** 
**Status:** in-progress

---
## Law 1 — Prediction (BEFORE reading)

*Solo título y headings, sin abrir el contenido del capítulo.*

> **Prediction:** Work with the basic of numpy library

---
## Active reading notes

*Notas durante la lectura. Solo lo que querés recordar — no transcribas. Para cada concepto agrego una cell de markdown + una de código si tiene sentido experimentar.*

### [Section name from the book]

## NumPy
- NUMerical PYthon
- NumPy provides a comprehensive and well-documented C API

In [11]:
# Perfomrance difference
import numpy as np

my_arr = np.arange(1_000_000)

my_list = list(range(1_000_000))

In [12]:
%timeit my_arr2 = my_arr * 2

2.31 ms ± 47.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
%timeit my_list2 = [x * 2 for x in my_list]

75 ms ± 423 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 4.1 The NumPy ndarray: A Multidimensional Array Object
- N-dimensional array object
- ndarray
- Fast a flexible container for large datasets ni Python.

In [18]:
import numpy as np

data = np.array([[1.5, -0.1, 3], [0, -3, 6.]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6. ]])

- Write mathematical operations with `data`

In [19]:
data * 10 # All elements multiply by 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  60.]])

In [21]:
data + data # All elements added to each other

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 12. ]])

- An ndarray is a generic multidimensional container for homogeneous data
- `shape` the size of each dimension
- `dtype` data type of the array

In [23]:
data.shape # In this case a 2x3 matrix

(2, 3)

In [24]:
data.dtype

dtype('float64')

## Creating ndarrays
- To create an array -> `array` function.
- Produces a new NumPy array containing the passed data.

In [26]:
data1 = [6, 7.55, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6.  , 7.55, 8.  , 0.  , 1.  ])

- Nested sequences

In [28]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
arr2.ndim # n-dimensions

2

In [31]:
arr2.shape

(2, 4)

- `dtype` tipo de dato

In [33]:
arr1.dtype

dtype('float64')

In [34]:
arr2.dtype

dtype('int64')

- Other functions to create arrays: `numpy.zeros` and `numpy.ones`

In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros((3,6)) # 3x6 matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [39]:
np.empty((2,3,2))

array([[[1.04732479e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.04082753e-047]],

       [[4.95915826e-090, 1.13017814e-042],
        [8.41434051e+164, 1.15389249e-071],
        [3.99910963e+252, 8.85276720e+165]]])

- `numpy.arangerange` this version is with values

In [40]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

| Function            | Description |
|--------------------|-------------|
| `array`            | Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default |
| `asarray`          | Convert input to ndarray, but do not copy if the input is already an ndarray |
| `arange`           | Like the built-in `range` but returns an ndarray instead of a list |
| `ones`, `ones_like`| Produce an array of all 1s with the given shape and data type; `ones_like` takes another array and produces a ones array of the same shape and data type |
| `zeros`, `zeros_like` | Like `ones` and `ones_like` but producing arrays of 0s instead |
| `empty`, `empty_like` | Create new arrays by allocating new memory, but do not populate with any values like `ones` and `zeros` |
| `full`, `full_like` | Produce an array of the given shape and data type with all values set to the indicated "fill value"; `full_like` takes another array and produces a filled array of the same shape and data type |
| `eye`, `identity`  | Create a square identity matrix |

## Data Types for ndarrays
- `dtype` contain the information the ndarray needs to interpret a chunk.

In [42]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [43]:
arr1.dtype

dtype('float64')

In [44]:
arr2.dtype

dtype('int32')

- Convert an array from one data type to another using ndarray's `astype`

In [45]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [51]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [52]:
 float_arr.dtype

dtype('float64')

In [54]:
# In that example, I convert from int to float
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [55]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

- Change from str to numeric form

In [60]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [61]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

## Arithmetic with NumPy Arrays

In [63]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [65]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [66]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
# Arithmetic operations with scalars propagate the scalar argument to each element in the array
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [68]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [69]:
# Comparisons between arrays of the same size yield Boolean arrays
arr2 = np.array([[0., 4., 1.], [7. ,2., 12. ]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [70]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [73]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr[5]

np.int64(5)

In [75]:
arr[5:8]

array([5, 6, 7])

In [79]:
# if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [81]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [83]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [84]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [85]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d[2]

array([7, 8, 9])

In [86]:
arr2d[0][2]

np.int64(3)

In [87]:
arr2d[0, 2]

np.int64(3)

![](https://wesmckinney.com/book/images/pda3_0401.png)

---
## Law 2 — Failure mode (AFTER reading)

> *¿En qué situación real esto me podría romper código en producción?*
> 


---
## Law 4 — Resumen 5 líneas (SIN MIRAR el libro)

*Cerrá el libro. Escribí 5 líneas SUSTANTIVAS — síntesis, no descripción. Si no podés, releé.*

1. 
2. 
3. 
4. 
5. 

---
## Open questions

*Lo que no quedó claro durante la lectura. Resolvé al final del capítulo o tracelas a la retro del Domingo.*

- [ ] 

---
## Honest reflections (ok if dirty)

*Esto va al repo público. Si te frustró algo, escribilo igual — eso es la marca del sprint.*

- 

---
## Insights propios

*Pensamientos tuyos sobre lo leído, no resúmenes del autor. Conexiones que viste, analogías, etc.*

- 

---
## Self-test antes de cerrar

*Contestá SIN MIRAR el libro. Si una respuesta es no, re-leé la sección.*

- [ ] (Pregunta 1 — algo que el capítulo te debería haber enseñado)
- [ ] (Pregunta 2)
- [ ] (Pregunta 3)
- [ ] (Pregunta 4)

---
## Connections

- Conecta con: Cap previo / sprint anchor / proyecto futuro
- Refuerza el concepto de: 
- Te prepara para Cap: 

---
## Cierre

Cuando todas las secciones estén llenas y el self-test esté ✅:

1. Marcar **Status: closed** arriba.
2. Marcar el chapter como `[x]` en `01-Python/books/README.md`.
3. Commit con mensaje: `"Ch XX (book): [topic] — closed"`.
4. Push.
5. Anotar 1 línea en `Key takeaways` del README del libro.