# Chapter 04 — NumPy Basics: Arrays and Vectorized Computation

**Book:** Python for Data Analysis (Wes McKinney, 3E)
**Date started:** 0226-05-04
**Date closed:** 
**Time invested:** 
**Status:** in-progress

---
## Law 1 — Prediction (BEFORE reading)

*Solo título y headings, sin abrir el contenido del capítulo.*

> **Prediction:** Work with the basic of numpy library

---
## Active reading notes

*Notas durante la lectura. Solo lo que querés recordar — no transcribas. Para cada concepto agrego una cell de markdown + una de código si tiene sentido experimentar.*

### [Section name from the book]

## NumPy
- NUMerical PYthon
- NumPy provides a comprehensive and well-documented C API

In [2]:
# Perfomrance difference
import numpy as np

my_arr = np.arange(1_000_000)

my_list = list(range(1_000_000))

In [3]:
%timeit my_arr2 = my_arr * 2

2.51 ms ± 108 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit my_list2 = [x * 2 for x in my_list]

79.9 ms ± 1.81 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 4.1 The NumPy ndarray: A Multidimensional Array Object
- N-dimensional array object
- ndarray
- Fast a flexible container for large datasets ni Python.

In [5]:
import numpy as np

data = np.array([[1.5, -0.1, 3], [0, -3, 6.]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6. ]])

- Write mathematical operations with `data`

In [6]:
data * 10 # All elements multiply by 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  60.]])

In [7]:
data + data # All elements added to each other

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 12. ]])

- An ndarray is a generic multidimensional container for homogeneous data
- `shape` the size of each dimension
- `dtype` data type of the array

In [8]:
data.shape # In this case a 2x3 matrix

(2, 3)

In [9]:
data.dtype

dtype('float64')

## Creating ndarrays
- To create an array -> `array` function.
- Produces a new NumPy array containing the passed data.

In [10]:
data1 = [6, 7.55, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6.  , 7.55, 8.  , 0.  , 1.  ])

- Nested sequences

In [11]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.ndim # n-dimensions

2

In [13]:
arr2.shape

(2, 4)

- `dtype` tipo de dato

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int64')

- Other functions to create arrays: `numpy.zeros` and `numpy.ones`

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,6)) # 3x6 matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.empty((2,3,2))

array([[[1.5454913e-311, 1.5454913e-311],
        [1.5454913e-311, 1.2697487e-321],
        [0.0000000e+000, 0.0000000e+000]],

       [[0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000]]])

- `numpy.arangerange` this version is with values

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

| Function            | Description |
|--------------------|-------------|
| `array`            | Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default |
| `asarray`          | Convert input to ndarray, but do not copy if the input is already an ndarray |
| `arange`           | Like the built-in `range` but returns an ndarray instead of a list |
| `ones`, `ones_like`| Produce an array of all 1s with the given shape and data type; `ones_like` takes another array and produces a ones array of the same shape and data type |
| `zeros`, `zeros_like` | Like `ones` and `ones_like` but producing arrays of 0s instead |
| `empty`, `empty_like` | Create new arrays by allocating new memory, but do not populate with any values like `ones` and `zeros` |
| `full`, `full_like` | Produce an array of the given shape and data type with all values set to the indicated "fill value"; `full_like` takes another array and produces a filled array of the same shape and data type |
| `eye`, `identity`  | Create a square identity matrix |

## Data Types for ndarrays
- `dtype` contain the information the ndarray needs to interpret a chunk.

In [20]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

- Convert an array from one data type to another using ndarray's `astype`

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [24]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [25]:
 float_arr.dtype

dtype('float64')

In [26]:
# In that example, I convert from int to float
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [27]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

- Change from str to numeric form

In [28]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [29]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

## Arithmetic with NumPy Arrays

In [31]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [33]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# Arithmetic operations with scalars propagate the scalar argument to each element in the array
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [35]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [36]:
# Comparisons between arrays of the same size yield Boolean arrays
arr2 = np.array([[0., 4., 1.], [7. ,2., 12. ]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [37]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [38]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5]

np.int64(5)

In [40]:
arr[5:8]

array([5, 6, 7])

In [41]:
# if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [42]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [43]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [44]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [45]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d[2]

array([7, 8, 9])

In [46]:
arr2d[0][2]

np.int64(3)

In [47]:
arr2d[0, 2]

np.int64(3)

![](https://wesmckinney.com/book/images/pda3_0401.png)

In [71]:
arr3d = np.array([
    [
        [1,2,3], [4,5,6]
    ], 
    [
        [7,8,9], [10, 11, 12]
    ]
])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d.shape

(2, 2, 3)

In [73]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[1, 0]

array([7, 8, 9])

In [78]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [79]:
x[0]

array([7, 8, 9])

In [80]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [82]:
arr[1:16]

array([ 1,  2,  3,  4, 64, 64, 64,  8,  9])

In [88]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [91]:
lower_dim_slice = arr2d[1, :2]
lower_dim_slice

array([4, 5])

In [92]:
lower_dim_slice.shape

(2,)

In [94]:
arr2d[:2, 2]

array([3, 6])

In [95]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [97]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

![](https://wesmckinney.com/book/images/pda3_0402.png)

### Indexación booleana

In [100]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [101]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [103]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [106]:
data[names == "Bob"] # En names, las posiciones [0] y [3] son True. Y esas posiciones en data son [4,7] y [0,0]

array([[4, 7],
       [0, 0]])

In [104]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [107]:
data[names == "Bob", 1]

array([7, 0])

In [108]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [109]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [110]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [114]:
cond = names == "Bob"
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [116]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [117]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [119]:
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

### Fancy Indexing
La indexación avanzada es un término adoptado por NumPy para describir la indexación mediante matrices de enteros. Supongamos que tenemos una matriz de 8 × 4:

In [121]:
arr = np.zeros((8, 4))

for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [122]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [123]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [125]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [127]:
arr[[1,5,7,2], 
    [0,3,1,2]] # -> [1,0] [5,3] [7,1] [2,2] -> [4,23,29,10]

array([ 4, 23, 29, 10])

In [131]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

### Transposing Arrays and Swapping Axes


In [132]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [134]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [135]:
# computing the inner matrix product using numpy.dot
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [137]:
arr.T

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [136]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [139]:
# The @ infix operator is another way to do matrix multiplication
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [140]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [141]:
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

## Pseudorandom Number Generation

In [143]:
samples = np.random.standard_normal(size=(4,4))
samples

array([[-0.02657635, -0.90251937, -0.09961814, -0.87939477],
       [-1.60348712, -0.39867443,  0.50245175,  1.61163058],
       [ 1.51271512, -0.32836323,  3.02211963,  1.401918  ],
       [ 0.35040238, -1.23093898, -1.23833717, -0.03531546]])

In [145]:
from random import normalvariate

N = 1_000_000

%timeit samples = [normalvariate(0, 1) for _ in range(N)]

849 ms ± 29.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [146]:
%timeit np.random.standard_normal(N)

32.7 ms ± 450 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [148]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))
type(rng)

numpy.random._generator.Generator

In [149]:
type(data)

numpy.ndarray

## Funciones universales: Funciones rápidas para matrices elemento a elemento


---
## Law 2 — Failure mode (AFTER reading)

> *¿En qué situación real esto me podría romper código en producción?*
> 


---
## Law 4 — Resumen 5 líneas (SIN MIRAR el libro)

*Cerrá el libro. Escribí 5 líneas SUSTANTIVAS — síntesis, no descripción. Si no podés, releé.*

1. 
2. 
3. 
4. 
5. 

---
## Open questions

*Lo que no quedó claro durante la lectura. Resolvé al final del capítulo o tracelas a la retro del Domingo.*

- [ ] 

---
## Honest reflections (ok if dirty)

*Esto va al repo público. Si te frustró algo, escribilo igual — eso es la marca del sprint.*

- 

---
## Insights propios

*Pensamientos tuyos sobre lo leído, no resúmenes del autor. Conexiones que viste, analogías, etc.*

- 

---
## Self-test antes de cerrar

*Contestá SIN MIRAR el libro. Si una respuesta es no, re-leé la sección.*

- [ ] (Pregunta 1 — algo que el capítulo te debería haber enseñado)
- [ ] (Pregunta 2)
- [ ] (Pregunta 3)
- [ ] (Pregunta 4)

---
## Connections

- Conecta con: Cap previo / sprint anchor / proyecto futuro
- Refuerza el concepto de: 
- Te prepara para Cap: 

---
## Cierre

Cuando todas las secciones estén llenas y el self-test esté ✅:

1. Marcar **Status: closed** arriba.
2. Marcar el chapter como `[x]` en `01-Python/books/README.md`.
3. Commit con mensaje: `"Ch XX (book): [topic] — closed"`.
4. Push.
5. Anotar 1 línea en `Key takeaways` del README del libro.