# Chapter 04 — NumPy Basics: Arrays and Vectorized Computation

**Book:** Python for Data Analysis (Wes McKinney, 3E)
**Date started:** 0226-05-04
**Date closed:** 
**Time invested:** 
**Status:** in-progress

---
## Law 1 — Prediction (BEFORE reading)

*Solo título y headings, sin abrir el contenido del capítulo.*

> **Prediction:** : I'm going to learn what an ndarray is, how to create one, how to index it, what mathematical operations it performs, and why it's faster than lists. I'll probably cover random number generation and linear algebra operations as well.

>PREDICTION 2: Re aprender Numpy otra vez, con otros recursos, mas visuales, para poder arraigar los conocimientos tanto de programacion como lo que realmente esta pasando por debajo.

## Resouce Number 1 - Jay Alammar Blog

[LINK](https://jalammar.github.io/visual-numpy/)

In [3]:
import numpy as np

In [4]:
data = np.array([1,2,3])

In [5]:
data

array([1, 2, 3])

In [6]:
data.max()

np.int64(3)

![image](https://jalammar.github.io/images/numpy/numpy-array.png)

## The N-dimensional array (ndarray)
[LINK A LA DOCUMENTACION DE NUMPY SOBRE ndarray](https://numpy.org/doc/stable/reference/arrays.ndarray.html)

In [10]:
# CREAR UN ARRAY PASANDOLE LOS VALORES `np.array()`
np.array([1,2,3])

array([1, 2, 3])

![Image](https://jalammar.github.io/images/numpy/create-numpy-array-1.png)

In [15]:
# INICIAR LOS VALORES DEL ARRAY AUTOMATICAMENTE PASANDOLE LA CANTIDAD DE VALORES QUE QUEREMOS GENERAR
np.ones(3)

array([1., 1., 1.])

![](./images/1.png)

In [12]:
np.zeros(3)

array([0., 0., 0.])

![](./images/2.png)

In [14]:
np.random.random(3)

array([0.0987843 , 0.95616487, 0.25997145])

![](./images/3.png)

### Aritmetics with Arrays

In [17]:
# CREAMOS 2 ARRAYS
data = np.array([1,2])
ones = np.ones(2)

![](https://jalammar.github.io/images/numpy/numpy-arrays-example-1.png)

In [18]:
data + ones

array([2., 3.])

![](https://jalammar.github.io/images/numpy/numpy-arrays-adding-1.png)

In [21]:
# LO MISMO APLICA PARA RESTAS, MULTIPLICACION y DIVISION
data * data

array([1, 4])

In [22]:
data / data

array([1., 1.])

In [23]:
data - ones

array([0., 1.])

In [24]:
# OPERACION ENTRE UN VECTOR Y UN ESCALAR
data * 1.6

array([1.6, 3.2])

![](https://jalammar.github.io/images/numpy/numpy-array-broadcast.png)

In [25]:
# NumPy aqui interpreto que esta operacion debia realizarse para cada celda. Este concepto se llama BROADCASTING.

### Indexation

In [30]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [31]:
data[0]

np.int64(1)

In [32]:
data[1]

np.int64(2)

In [33]:
data[0:2]

array([1, 2])

In [34]:
data[1:]

array([2, 3])

![](https://jalammar.github.io/images/numpy/numpy-array-slice.png)

### Aggregation

In [35]:
### FUNCIONES DE AGREGACION
data.max() # Retorna el maximo valor en el array

np.int64(3)

In [37]:
data.min() # Retorna el minimo valor en el array

np.int64(1)

In [39]:
data.sum() # Retorna la suma de todos los valores en el array

np.int64(6)

![](https://jalammar.github.io/images/numpy/numpy-array-aggregation.png)

#### OTRAS FUNCIONES
- `mean` obtener el promedio.  
- `prod` obtener el resultado de multiplicar todos los elementos juntos.  
- `std` obtener la desviación estándar.  

### More Dimensions 

In [57]:
### Creating Matrixs
np.array([
    [1,2],
    [3,4]
])

array([[1, 2],
       [3, 4]])

![](https://jalammar.github.io/images/numpy/numpy-array-create-2d.png)

In [55]:
### TAMBIEN PODEMOS USAR LOS MISMOS METODOS PARA CREARLAS DESDE CERO DANDOLE LAS DIMENSIONES
np.ones((3,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [51]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
np.random.random((3,2))

array([[0.19250975, 0.19507293],
       [0.68221919, 0.8212304 ],
       [0.64527638, 0.68705565]])

![](https://jalammar.github.io/images/numpy/numpy-matrix-ones-zeros-random.png)

### Matrix Arithmetic

In [59]:
data = np.array([[1,2],[3,4]])
ones = np.ones((2,2))

In [62]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


![](https://jalammar.github.io/images/numpy/numpy-matrix-arithmetic.png)

In [66]:
### Podemos realizar estas operaciones aritméticas en matrices de diferente tamaño solo si la diferencia de dimensión es uno
ones_row = np.array([1,1])
data = np.array([[1,2], [3,4], [5,6]])

In [67]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

![](https://jalammar.github.io/images/numpy/numpy-matrix-broadcast.png)

### Producto Escalar

In [71]:
data = np.array([[1,2,3]])
data

array([[1, 2, 3]])

In [78]:
data.dot([[1,10],[100, 1000], [10000,100000]])

array([[ 30201, 302010]])

![](https://jalammar.github.io/images/numpy/numpy-matrix-dot-product-1.png)
![](https://jalammar.github.io/images/numpy/numpy-matrix-dot-product-2.png)

### Matrix Indexing

In [81]:
data = np.array([[1,2], [3,4], [5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [82]:
data[0,1]

np.int64(2)

In [83]:
data[1:3]

array([[3, 4],
       [5, 6]])

![](https://jalammar.github.io/images/numpy/numpy-matrix-indexing.png)

### Matrix Aggregation

In [84]:
data = np.array([[1,2], [3,4], [5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
data.max()

np.int64(6)

In [86]:
data.min()

np.int64(1)

In [87]:
data.sum()

np.int64(21)

![](https://jalammar.github.io/images/numpy/numpy-matrix-aggregation-1.png)

In [88]:
# No solo podemos agregar todos los valores de una matriz, sino que también podemos agregarlos a través de las filas o columnas utilizando el parámetro axis
data.max(axis=0) # Busca el maximo de cada columna

array([5, 6])

In [90]:
data.max(axis=1) # Busca el maximo de cada fila)

array([2, 4, 6])

![](https://jalammar.github.io/images/numpy/numpy-matrix-aggregation-4.png)

### Transposing and Reshaping

In [93]:
# Rotarla (TRANSPOSICION)
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [95]:
# Cambiar las dimensiones de una matriz (RESHAPING)

In [97]:
data = np.array([[1],[2],[3],[4],[5],[6]])
data

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [98]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

![](https://jalammar.github.io/images/numpy/numpy-reshape.png)

### More Dimensions

In [101]:
data = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
data

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

![](https://jalammar.github.io/images/numpy/numpy-3d-array.png)

In [103]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [104]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [105]:
np.random.random((4,3,2))

array([[[0.25341418, 0.25118628],
        [0.34425476, 0.20418852],
        [0.90729674, 0.50886183]],

       [[0.11288458, 0.12178294],
        [0.78560317, 0.15329838],
        [0.88284872, 0.17245259]],

       [[0.04172958, 0.00610796],
        [0.30778375, 0.36590762],
        [0.35988968, 0.56586607]],

       [[0.73984964, 0.48151644],
        [0.50702044, 0.99003397],
        [0.40570292, 0.17741374]]])

![](https://jalammar.github.io/images/numpy/numpy-3d-array-creation.png)

### Uso practico de NumPy

Fórmula del error cuadrático medio, fundamental para los modelos de aprendizaje automático supervisado que abordan problemas de regresión

![](https://jalammar.github.io/images/numpy/mean-square-error-formula.png)

In [112]:
n = 3
predictions = np.array([[1],[1],[1]])
labels = np.array([[1],[2],[3]])

error = (1/n) * np.sum(np.square(predictions - labels))
error

np.float64(1.6666666666666665)

![](https://jalammar.github.io/images/numpy/numpy-mean-square-error-formula.png)
![](https://jalammar.github.io/images/numpy/numpy-mse-1.png)
![](https://jalammar.github.io/images/numpy/numpy-mse-2.png)
![](https://jalammar.github.io/images/numpy/numpy-mse-3.png)  
![](https://jalammar.github.io/images/numpy/numpy-mse-4.png)